version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/mercury/django_static
            - media_volume:/app/mercury/media
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on: 
            - mercury
        command: "/bin/sh -c 'nginx -g \"daemon off;\"'"
    mercury:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/mercury/Dockerfile
        entrypoint: /app/docker/mercury/entrypoint.sh
        volumes:
            - ${NOTEBOOKS_PATH}:/app/notebooks
            - static_volume:/app/mercury/django_static
            - media_volume:/app/mercury/media
        expose:
            - 8000     
        environment:
            DEBUG: ${DEBUG}
            SERVE_STATIC: ${SERVE_STATIC}
            DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
            DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
            DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
            SECRET_KEY: ${SECRET_KEY}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
            WELCOME: ${WELCOME}

volumes:
    static_volume: {}
    media_volume: {}